name: ci

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # actions/checkout downloads the repo files
      - uses: actions/checkout@v4

      # installs Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          pip install ruff

      - name: Check linting
        run: ruff check .

      - name: Check formatting
        run: ruff format --check .

      - name: run docker build
        run: docker build -t app .
